# -*- coding: utf-8 -*-

from odoo import models, fields, api, _
from odoo.exceptions import UserError
from datetime import datetime,timedelta,date
from odoo.tools import DEFAULT_SERVER_DATETIME_FORMAT
from odoo.exceptions import AccessError, UserError, RedirectWarning, ValidationError, Warning



class DebitoMotivo(models.Model):
	_name='debito.motivo'
	
	codigo = fields.Char()
	name = fields.Char()
	company_id = fields.Many2one('res.company','Compa√±ia', required=True, index=True, default=lambda self: self.env.user.company_id.id)

	

